// Code generated by fieldaccessgen. DO NOT EDIT.

package value

import "znkr.io/writst/internal/names"
import "znkr.io/writst/name"

func (n *Document) Field(name name.Name) Value {
	switch name {
	case names.Title:
		if n.Title == "" {
			return nil
		}
		return Str(n.Title)
	case names.Date:
		if n.Date == nil {
			return nil
		}
		return *n.Date
	case names.Body:
		return n.Body
	default:
		return nil
	}
}

func (n *Document) HasField(name name.Name) bool {
	switch name {
	case names.Title:
		return n.Title != ""
	case names.Date:
		return n.Date != nil
	case names.Body:
		return true
	default:
		return false
	}
}

func (n *Document) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Title); f != nil {
		fields.Elems.Put(Str(names.Title.String()), f)
	}
	if f := n.Field(names.Date); f != nil {
		fields.Elems.Put(Str(names.Date.String()), f)
	}
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	return fields
}

func (n *Document) SetLabel(label *Label) *Label {
	return nil
}

func (n *Document) GetLabel() *Label {
	return nil
}

func (n *Document) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Emph) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Emph) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Emph) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Emph) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Emph) GetLabel() *Label {
	return n.Label
}

func (n *Emph) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Enum) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Enum) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Enum) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Enum) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Enum) GetLabel() *Label {
	return n.Label
}

func (n *Enum) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *EnumItem) Field(name name.Name) Value {
	switch name {
	case names.Number:
		if n.Number < 0 {
			return nil
		}
		return Int(n.Number)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *EnumItem) HasField(name name.Name) bool {
	switch name {
	case names.Number:
		return n.Number >= 0
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *EnumItem) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Number); f != nil {
		fields.Elems.Put(Str(names.Number.String()), f)
	}
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *EnumItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *EnumItem) GetLabel() *Label {
	return n.Label
}

func (n *EnumItem) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Equation) Field(name name.Name) Value {
	switch name {
	case names.Block:
		return Bool(n.Block)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Equation) HasField(name name.Name) bool {
	switch name {
	case names.Block:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Equation) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Equation) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Equation) GetLabel() *Label {
	return n.Label
}

func (n *Equation) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Footnote) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Footnote) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Footnote) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Footnote) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Footnote) GetLabel() *Label {
	return n.Label
}

func (n *Footnote) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *HSpace) Field(name name.Name) Value {
	switch name {
	case names.Amount:
		return n.Amount
	default:
		return nil
	}
}

func (n *HSpace) HasField(name name.Name) bool {
	switch name {
	case names.Amount:
		return true
	default:
		return false
	}
}

func (n *HSpace) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Amount.String()), n.Field(names.Amount))
	return fields
}

func (n *HSpace) SetLabel(label *Label) *Label {
	return nil
}

func (n *HSpace) GetLabel() *Label {
	return nil
}

func (n *HSpace) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *HTMLElem) Field(name name.Name) Value {
	switch name {
	case names.Tag:
		return Str(n.Tag)
	case names.Attrs:
		if n.Attrs == nil {
			return nil
		}
		return n.Attrs
	case names.Body:
		if n.Body == nil {
			return nil
		}
		return n.Body
	case names.Block:
		return Bool(n.Block)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *HTMLElem) HasField(name name.Name) bool {
	switch name {
	case names.Tag:
		return true
	case names.Attrs:
		return n.Attrs != nil
	case names.Body:
		return n.Body != nil
	case names.Block:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *HTMLElem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Tag.String()), n.Field(names.Tag))
	if f := n.Field(names.Attrs); f != nil {
		fields.Elems.Put(Str(names.Attrs.String()), f)
	}
	if f := n.Field(names.Body); f != nil {
		fields.Elems.Put(Str(names.Body.String()), f)
	}
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *HTMLElem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *HTMLElem) GetLabel() *Label {
	return n.Label
}

func (n *HTMLElem) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Heading) Field(name name.Name) Value {
	switch name {
	case names.Depth:
		return Int(n.Depth)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Heading) HasField(name name.Name) bool {
	switch name {
	case names.Depth:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Heading) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Depth.String()), n.Field(names.Depth))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Heading) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Heading) GetLabel() *Label {
	return n.Label
}

func (n *Heading) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Image) Field(name name.Name) Value {
	switch name {
	case names.Path:
		return Str(n.Path)
	case names.Alt:
		if n.Alt == "" {
			return nil
		}
		return Str(n.Alt)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Image) HasField(name name.Name) bool {
	switch name {
	case names.Path:
		return true
	case names.Alt:
		return n.Alt != ""
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Image) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Path.String()), n.Field(names.Path))
	if f := n.Field(names.Alt); f != nil {
		fields.Elems.Put(Str(names.Alt.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Image) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Image) GetLabel() *Label {
	return n.Label
}

func (n *Image) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Linebreak) Field(name name.Name) Value {
	return nil
}

func (n *Linebreak) HasField(name name.Name) bool {
	return false
}

func (n *Linebreak) Fields() *Dict {
	return new(Dict)
}

func (n *Linebreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Linebreak) GetLabel() *Label {
	return nil
}

func (n *Linebreak) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Link) Field(name name.Name) Value {
	switch name {
	case names.Dest:
		return Str(n.Dest)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Link) HasField(name name.Name) bool {
	switch name {
	case names.Dest:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Link) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Dest.String()), n.Field(names.Dest))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Link) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Link) GetLabel() *Label {
	return n.Label
}

func (n *Link) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *List) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *List) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *List) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *List) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *List) GetLabel() *Label {
	return n.Label
}

func (n *List) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *ListItem) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *ListItem) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *ListItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *ListItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *ListItem) GetLabel() *Label {
	return n.Label
}

func (n *ListItem) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *MathAccent) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Accent:
		return Str(n.Accent)
	case names.Size:
		if n.Size == nil {
			return nil
		}
		return n.Size
	case names.Dotless:
		return Bool(n.Dotless)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAccent) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Accent:
		return true
	case names.Size:
		return n.Size != nil
	case names.Dotless:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAccent) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	fields.Elems.Put(Str(names.Accent.String()), n.Field(names.Accent))
	if f := n.Field(names.Size); f != nil {
		fields.Elems.Put(Str(names.Size.String()), f)
	}
	fields.Elems.Put(Str(names.Dotless.String()), n.Field(names.Dotless))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAccent) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAccent) GetLabel() *Label {
	return n.Label
}

func (n *MathAccent) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Base != nil && !n.Base.walk(yield) {
		return false
	}
	return true
}

func (n *MathAlignPoint) Field(name name.Name) Value {
	switch name {
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAlignPoint) HasField(name name.Name) bool {
	switch name {
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAlignPoint) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAlignPoint) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAlignPoint) GetLabel() *Label {
	return n.Label
}

func (n *MathAlignPoint) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *MathAttach) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Top:
		if n.Top == nil {
			return nil
		}
		return n.Top
	case names.Bottom:
		if n.Bottom == nil {
			return nil
		}
		return n.Bottom
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAttach) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Top:
		return n.Top != nil
	case names.Bottom:
		return n.Bottom != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAttach) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	if f := n.Field(names.Top); f != nil {
		fields.Elems.Put(Str(names.Top.String()), f)
	}
	if f := n.Field(names.Bottom); f != nil {
		fields.Elems.Put(Str(names.Bottom.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAttach) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAttach) GetLabel() *Label {
	return n.Label
}

func (n *MathAttach) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Base != nil && !n.Base.walk(yield) {
		return false
	}
	if n.Top != nil && !n.Top.walk(yield) {
		return false
	}
	if n.Bottom != nil && !n.Bottom.walk(yield) {
		return false
	}
	return true
}

func (n *MathCancel) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Angle:
		if n.Angle == nil {
			return nil
		}
		return n.Angle
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathCancel) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Angle:
		return n.Angle != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathCancel) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Angle); f != nil {
		fields.Elems.Put(Str(names.Angle.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathCancel) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathCancel) GetLabel() *Label {
	return n.Label
}

func (n *MathCancel) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *MathCases) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathCases) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathCases) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathCases) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathCases) GetLabel() *Label {
	return n.Label
}

func (n *MathCases) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *MathDelimited) Field(name name.Name) Value {
	switch name {
	case names.Open:
		return n.Open
	case names.Body:
		return n.Body
	case names.Close:
		return n.Close
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathDelimited) HasField(name name.Name) bool {
	switch name {
	case names.Open:
		return true
	case names.Body:
		return true
	case names.Close:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathDelimited) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Open.String()), n.Field(names.Open))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	fields.Elems.Put(Str(names.Close.String()), n.Field(names.Close))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathDelimited) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathDelimited) GetLabel() *Label {
	return n.Label
}

func (n *MathDelimited) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Open != nil && !n.Open.walk(yield) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	if n.Close != nil && !n.Close.walk(yield) {
		return false
	}
	return true
}

func (n *MathFrac) Field(name name.Name) Value {
	switch name {
	case names.Num:
		return n.Num
	case names.Denom:
		return n.Denom
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathFrac) HasField(name name.Name) bool {
	switch name {
	case names.Num:
		return true
	case names.Denom:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathFrac) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Num.String()), n.Field(names.Num))
	fields.Elems.Put(Str(names.Denom.String()), n.Field(names.Denom))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathFrac) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathFrac) GetLabel() *Label {
	return n.Label
}

func (n *MathFrac) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Num != nil && !n.Num.walk(yield) {
		return false
	}
	if n.Denom != nil && !n.Denom.walk(yield) {
		return false
	}
	return true
}

func (n *MathMat) Field(name name.Name) Value {
	switch name {
	case names.Rows:
		vs := make([]Value, len(n.Rows))
		for i, row := range n.Rows {
			rvs := make([]Value, len(row))
			for j, v := range row {
				rvs[j] = v
			}
			vs[i] = &Array{Elems: rvs}
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathMat) HasField(name name.Name) bool {
	switch name {
	case names.Rows:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathMat) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Rows.String()), n.Field(names.Rows))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathMat) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathMat) GetLabel() *Label {
	return n.Label
}

func (n *MathMat) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, row := range n.Rows {
		for _, c := range row {
			if !c.walk(yield) {
				return false
			}
		}
	}
	return true
}

func (n *MathOp) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return n.Text
	case names.Limits:
		return Bool(n.Limits)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathOp) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Limits:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathOp) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	fields.Elems.Put(Str(names.Limits.String()), n.Field(names.Limits))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathOp) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathOp) GetLabel() *Label {
	return n.Label
}

func (n *MathOp) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Text != nil && !n.Text.walk(yield) {
		return false
	}
	return true
}

func (n *MathPrimes) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Count:
		return Int(n.Count)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathPrimes) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Count:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathPrimes) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	fields.Elems.Put(Str(names.Count.String()), n.Field(names.Count))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathPrimes) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathPrimes) GetLabel() *Label {
	return n.Label
}

func (n *MathPrimes) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Base != nil && !n.Base.walk(yield) {
		return false
	}
	return true
}

func (n *MathRoot) Field(name name.Name) Value {
	switch name {
	case names.Index:
		if n.Index == nil {
			return nil
		}
		return n.Index
	case names.Radicand:
		return n.Radicand
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathRoot) HasField(name name.Name) bool {
	switch name {
	case names.Index:
		return n.Index != nil
	case names.Radicand:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathRoot) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Index); f != nil {
		fields.Elems.Put(Str(names.Index.String()), f)
	}
	fields.Elems.Put(Str(names.Radicand.String()), n.Field(names.Radicand))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathRoot) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathRoot) GetLabel() *Label {
	return n.Label
}

func (n *MathRoot) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Index != nil && !n.Index.walk(yield) {
		return false
	}
	if n.Radicand != nil && !n.Radicand.walk(yield) {
		return false
	}
	return true
}

func (n *MathText) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return Str(n.Text)
	case names.Bold:
		if n.Bold == nil {
			return nil
		}
		return n.Bold
	case names.Italic:
		if n.Italic == nil {
			return nil
		}
		return n.Italic
	case names.Variant:
		if n.Variant == nil {
			return nil
		}
		return n.Variant
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathText) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Bold:
		return n.Bold != nil
	case names.Italic:
		return n.Italic != nil
	case names.Variant:
		return n.Variant != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathText) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	if f := n.Field(names.Bold); f != nil {
		fields.Elems.Put(Str(names.Bold.String()), f)
	}
	if f := n.Field(names.Italic); f != nil {
		fields.Elems.Put(Str(names.Italic.String()), f)
	}
	if f := n.Field(names.Variant); f != nil {
		fields.Elems.Put(Str(names.Variant.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathText) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathText) GetLabel() *Label {
	return n.Label
}

func (n *MathText) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *MathUnderline) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathUnderline) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathUnderline) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathUnderline) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathUnderline) GetLabel() *Label {
	return n.Label
}

func (n *MathUnderline) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *MathVec) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathVec) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathVec) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathVec) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathVec) GetLabel() *Label {
	return n.Label
}

func (n *MathVec) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *Metadata) Field(name name.Name) Value {
	switch name {
	case names.Value:
		return n.Value
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Metadata) HasField(name name.Name) bool {
	switch name {
	case names.Value:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Metadata) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Value.String()), n.Field(names.Value))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Metadata) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Metadata) GetLabel() *Label {
	return n.Label
}

func (n *Metadata) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Par) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Par) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Par) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Par) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Par) GetLabel() *Label {
	return n.Label
}

func (n *Par) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Parbreak) Field(name name.Name) Value {
	return nil
}

func (n *Parbreak) HasField(name name.Name) bool {
	return false
}

func (n *Parbreak) Fields() *Dict {
	return new(Dict)
}

func (n *Parbreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Parbreak) GetLabel() *Label {
	return nil
}

func (n *Parbreak) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Raw) Field(name name.Name) Value {
	switch name {
	case names.Block:
		return Bool(n.Block)
	case names.Lang:
		if n.Lang == "" {
			return nil
		}
		return Str(n.Lang)
	case names.Text:
		return Str(n.Text)
	default:
		return nil
	}
}

func (n *Raw) HasField(name name.Name) bool {
	switch name {
	case names.Block:
		return true
	case names.Lang:
		return n.Lang != ""
	case names.Text:
		return true
	default:
		return false
	}
}

func (n *Raw) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	if f := n.Field(names.Lang); f != nil {
		fields.Elems.Put(Str(names.Lang.String()), f)
	}
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	return fields
}

func (n *Raw) SetLabel(label *Label) *Label {
	return nil
}

func (n *Raw) GetLabel() *Label {
	return nil
}

func (n *Raw) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Ref) Field(name name.Name) Value {
	switch name {
	case names.Target:
		return Str(n.Target.String())
	case names.Supplement:
		if n.Supplement == nil {
			return nil
		}
		return n.Supplement
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Ref) HasField(name name.Name) bool {
	switch name {
	case names.Target:
		return true
	case names.Supplement:
		return n.Supplement != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Ref) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Target.String()), n.Field(names.Target))
	if f := n.Field(names.Supplement); f != nil {
		fields.Elems.Put(Str(names.Supplement.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Ref) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Ref) GetLabel() *Label {
	return n.Label
}

func (n *Ref) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Supplement != nil && !n.Supplement.walk(yield) {
		return false
	}
	return true
}

func (n *Sequence) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Sequence) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Sequence) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Sequence) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Sequence) GetLabel() *Label {
	return n.Label
}

func (n *Sequence) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *SmartQuote) Field(name name.Name) Value {
	switch name {
	case names.Double:
		return Bool(n.Double)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *SmartQuote) HasField(name name.Name) bool {
	switch name {
	case names.Double:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *SmartQuote) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Double.String()), n.Field(names.Double))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *SmartQuote) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *SmartQuote) GetLabel() *Label {
	return n.Label
}

func (n *SmartQuote) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Strong) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Strong) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Strong) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Strong) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Strong) GetLabel() *Label {
	return n.Label
}

func (n *Strong) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}

func (n *Table) Field(name name.Name) Value {
	switch name {
	case names.Columns:
		return Int(n.Columns)
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Table) HasField(name name.Name) bool {
	switch name {
	case names.Columns:
		return true
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Table) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Columns.String()), n.Field(names.Columns))
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Table) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Table) GetLabel() *Label {
	return n.Label
}

func (n *Table) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *TableHeader) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *TableHeader) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *TableHeader) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *TableHeader) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *TableHeader) GetLabel() *Label {
	return n.Label
}

func (n *TableHeader) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *TermItem) Field(name name.Name) Value {
	switch name {
	case names.Term:
		return n.Term
	case names.Description:
		return n.Description
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *TermItem) HasField(name name.Name) bool {
	switch name {
	case names.Term:
		return true
	case names.Description:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *TermItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Term.String()), n.Field(names.Term))
	fields.Elems.Put(Str(names.Description.String()), n.Field(names.Description))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *TermItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *TermItem) GetLabel() *Label {
	return n.Label
}

func (n *TermItem) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Term != nil && !n.Term.walk(yield) {
		return false
	}
	if n.Description != nil && !n.Description.walk(yield) {
		return false
	}
	return true
}

func (n *Terms) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Terms) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Terms) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Terms) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Terms) GetLabel() *Label {
	return n.Label
}

func (n *Terms) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	for _, c := range n.Children {
		if !c.walk(yield) {
			return false
		}
	}
	return true
}

func (n *Text) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return Str(n.Text)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Text) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Text) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Text) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Text) GetLabel() *Label {
	return n.Label
}

func (n *Text) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	return true
}

func (n *Underline) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Underline) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Underline) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Underline) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Underline) GetLabel() *Label {
	return n.Label
}

func (n *Underline) walk(yield func(Content) bool) bool {
	if !yield(n) {
		return false
	}
	if n.Body != nil && !n.Body.walk(yield) {
		return false
	}
	return true
}
