// Code generated by fieldaccessgen. DO NOT EDIT.

package value

import "znkr.io/markst/internal/names"
import "znkr.io/markst/name"

// ElemKind identifies a content element's type, one constant per element.
// It is what a [KindSet] holds and what a walk filters on.
type ElemKind uint8

const (
	KindCustom ElemKind = iota
	KindDocument
	KindEmph
	KindEnum
	KindEnumItem
	KindEquation
	KindFootnote
	KindHSpace
	KindHTMLElem
	KindHeading
	KindImage
	KindLinebreak
	KindLink
	KindList
	KindListItem
	KindMathAccent
	KindMathAlignPoint
	KindMathAttach
	KindMathCancel
	KindMathCases
	KindMathFrac
	KindMathLr
	KindMathMat
	KindMathMid
	KindMathOp
	KindMathPrimes
	KindMathRoot
	KindMathText
	KindMathUnderline
	KindMathVec
	KindMetadata
	KindPar
	KindParbreak
	KindRaw
	KindRef
	KindSequence
	KindSmartQuote
	KindStateUpdate
	KindStrong
	KindStyleUpdate
	KindStyled
	KindTable
	KindTableHeader
	KindTermItem
	KindTerms
	KindText
	KindUnderline

	// numElemKinds is the number of element kinds. A KindSet holds one bit
	// per kind, so it must not exceed 64; TestKindSetFits checks that.
	numElemKinds
)

func (n *Document) Kind() ElemKind { return KindDocument }

func (n *Document) Field(name name.Name) Value {
	switch name {
	case names.Title:
		if n.Title == "" {
			return nil
		}
		return Str(n.Title)
	case names.Date:
		if n.Date == nil {
			return nil
		}
		return *n.Date
	case names.Body:
		return n.Body
	default:
		return nil
	}
}

func (n *Document) HasField(name name.Name) bool {
	switch name {
	case names.Title:
		return n.Title != ""
	case names.Date:
		return n.Date != nil
	case names.Body:
		return true
	default:
		return false
	}
}

func (n *Document) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Title); f != nil {
		fields.Elems.Put(Str(names.Title.String()), f)
	}
	if f := n.Field(names.Date); f != nil {
		fields.Elems.Put(Str(names.Date.String()), f)
	}
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	return fields
}

func (n *Document) SetLabel(label *Label) *Label {
	return nil
}

func (n *Document) GetLabel() *Label {
	return nil
}

func (n *Document) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindDocument) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Emph) Kind() ElemKind { return KindEmph }

func (n *Emph) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Emph) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Emph) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Emph) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Emph) GetLabel() *Label {
	return n.Label
}

func (n *Emph) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindEmph) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Enum) Kind() ElemKind { return KindEnum }

func (n *Enum) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Enum) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Enum) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Enum) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Enum) GetLabel() *Label {
	return n.Label
}

func (n *Enum) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindEnum) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *EnumItem) Kind() ElemKind { return KindEnumItem }

func (n *EnumItem) Field(name name.Name) Value {
	switch name {
	case names.Number:
		if n.Number < 0 {
			return nil
		}
		return Int(n.Number)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *EnumItem) HasField(name name.Name) bool {
	switch name {
	case names.Number:
		return n.Number >= 0
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *EnumItem) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Number); f != nil {
		fields.Elems.Put(Str(names.Number.String()), f)
	}
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *EnumItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *EnumItem) GetLabel() *Label {
	return n.Label
}

func (n *EnumItem) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindEnumItem) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Equation) Kind() ElemKind { return KindEquation }

func (n *Equation) Field(name name.Name) Value {
	switch name {
	case names.Block:
		return Bool(n.Block)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Equation) HasField(name name.Name) bool {
	switch name {
	case names.Block:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Equation) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Equation) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Equation) GetLabel() *Label {
	return n.Label
}

func (n *Equation) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindEquation) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Footnote) Kind() ElemKind { return KindFootnote }

func (n *Footnote) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Footnote) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Footnote) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Footnote) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Footnote) GetLabel() *Label {
	return n.Label
}

func (n *Footnote) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindFootnote) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *HSpace) Kind() ElemKind { return KindHSpace }

func (n *HSpace) Field(name name.Name) Value {
	switch name {
	case names.Amount:
		return n.Amount
	default:
		return nil
	}
}

func (n *HSpace) HasField(name name.Name) bool {
	switch name {
	case names.Amount:
		return true
	default:
		return false
	}
}

func (n *HSpace) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Amount.String()), n.Field(names.Amount))
	return fields
}

func (n *HSpace) SetLabel(label *Label) *Label {
	return nil
}

func (n *HSpace) GetLabel() *Label {
	return nil
}

func (n *HSpace) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindHSpace) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *HTMLElem) Kind() ElemKind { return KindHTMLElem }

func (n *HTMLElem) Field(name name.Name) Value {
	switch name {
	case names.Tag:
		return Str(n.Tag)
	case names.Attrs:
		if n.Attrs == nil {
			return nil
		}
		return n.Attrs
	case names.Body:
		if n.Body == nil {
			return nil
		}
		return n.Body
	case names.Block:
		return Bool(n.Block)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *HTMLElem) HasField(name name.Name) bool {
	switch name {
	case names.Tag:
		return true
	case names.Attrs:
		return n.Attrs != nil
	case names.Body:
		return n.Body != nil
	case names.Block:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *HTMLElem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Tag.String()), n.Field(names.Tag))
	if f := n.Field(names.Attrs); f != nil {
		fields.Elems.Put(Str(names.Attrs.String()), f)
	}
	if f := n.Field(names.Body); f != nil {
		fields.Elems.Put(Str(names.Body.String()), f)
	}
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *HTMLElem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *HTMLElem) GetLabel() *Label {
	return n.Label
}

func (n *HTMLElem) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindHTMLElem) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Heading) Kind() ElemKind { return KindHeading }

func (n *Heading) Field(name name.Name) Value {
	switch name {
	case names.Depth:
		return Int(n.Depth)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Heading) HasField(name name.Name) bool {
	switch name {
	case names.Depth:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Heading) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Depth.String()), n.Field(names.Depth))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Heading) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Heading) GetLabel() *Label {
	return n.Label
}

func (n *Heading) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindHeading) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Image) Kind() ElemKind { return KindImage }

func (n *Image) Field(name name.Name) Value {
	switch name {
	case names.Path:
		return Str(n.Path)
	case names.Alt:
		if n.Alt == "" {
			return nil
		}
		return Str(n.Alt)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Image) HasField(name name.Name) bool {
	switch name {
	case names.Path:
		return true
	case names.Alt:
		return n.Alt != ""
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Image) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Path.String()), n.Field(names.Path))
	if f := n.Field(names.Alt); f != nil {
		fields.Elems.Put(Str(names.Alt.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Image) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Image) GetLabel() *Label {
	return n.Label
}

func (n *Image) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindImage) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Linebreak) Kind() ElemKind { return KindLinebreak }

func (n *Linebreak) Field(name name.Name) Value {
	return nil
}

func (n *Linebreak) HasField(name name.Name) bool {
	return false
}

func (n *Linebreak) Fields() *Dict {
	return new(Dict)
}

func (n *Linebreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Linebreak) GetLabel() *Label {
	return nil
}

func (n *Linebreak) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindLinebreak) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Link) Kind() ElemKind { return KindLink }

func (n *Link) Field(name name.Name) Value {
	switch name {
	case names.Dest:
		return Str(n.Dest)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Link) HasField(name name.Name) bool {
	switch name {
	case names.Dest:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Link) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Dest.String()), n.Field(names.Dest))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Link) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Link) GetLabel() *Label {
	return n.Label
}

func (n *Link) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindLink) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *List) Kind() ElemKind { return KindList }

func (n *List) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *List) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *List) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *List) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *List) GetLabel() *Label {
	return n.Label
}

func (n *List) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindList) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *ListItem) Kind() ElemKind { return KindListItem }

func (n *ListItem) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *ListItem) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *ListItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *ListItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *ListItem) GetLabel() *Label {
	return n.Label
}

func (n *ListItem) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindListItem) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathAccent) Kind() ElemKind { return KindMathAccent }

func (n *MathAccent) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Accent:
		return Str(n.Accent)
	case names.Size:
		if n.Size == nil {
			return nil
		}
		return n.Size
	case names.Dotless:
		return Bool(n.Dotless)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAccent) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Accent:
		return true
	case names.Size:
		return n.Size != nil
	case names.Dotless:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAccent) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	fields.Elems.Put(Str(names.Accent.String()), n.Field(names.Accent))
	if f := n.Field(names.Size); f != nil {
		fields.Elems.Put(Str(names.Size.String()), f)
	}
	fields.Elems.Put(Str(names.Dotless.String()), n.Field(names.Dotless))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAccent) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAccent) GetLabel() *Label {
	return n.Label
}

func (n *MathAccent) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathAccent) && !w.visit() {
		return w.live()
	}
	if n.Base != nil && !n.Base.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathAlignPoint) Kind() ElemKind { return KindMathAlignPoint }

func (n *MathAlignPoint) Field(name name.Name) Value {
	switch name {
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAlignPoint) HasField(name name.Name) bool {
	switch name {
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAlignPoint) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAlignPoint) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAlignPoint) GetLabel() *Label {
	return n.Label
}

func (n *MathAlignPoint) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathAlignPoint) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *MathAttach) Kind() ElemKind { return KindMathAttach }

func (n *MathAttach) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Top:
		if n.Top == nil {
			return nil
		}
		return n.Top
	case names.Bottom:
		if n.Bottom == nil {
			return nil
		}
		return n.Bottom
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathAttach) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Top:
		return n.Top != nil
	case names.Bottom:
		return n.Bottom != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathAttach) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	if f := n.Field(names.Top); f != nil {
		fields.Elems.Put(Str(names.Top.String()), f)
	}
	if f := n.Field(names.Bottom); f != nil {
		fields.Elems.Put(Str(names.Bottom.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathAttach) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathAttach) GetLabel() *Label {
	return n.Label
}

func (n *MathAttach) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathAttach) && !w.visit() {
		return w.live()
	}
	if n.Base != nil && !n.Base.inspect(w) {
		return false
	}
	if n.Top != nil && !n.Top.inspect(w) {
		return false
	}
	if n.Bottom != nil && !n.Bottom.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathCancel) Kind() ElemKind { return KindMathCancel }

func (n *MathCancel) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Angle:
		if n.Angle == nil {
			return nil
		}
		return n.Angle
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathCancel) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Angle:
		return n.Angle != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathCancel) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Angle); f != nil {
		fields.Elems.Put(Str(names.Angle.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathCancel) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathCancel) GetLabel() *Label {
	return n.Label
}

func (n *MathCancel) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathCancel) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathCases) Kind() ElemKind { return KindMathCases }

func (n *MathCases) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathCases) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathCases) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathCases) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathCases) GetLabel() *Label {
	return n.Label
}

func (n *MathCases) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathCases) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *MathFrac) Kind() ElemKind { return KindMathFrac }

func (n *MathFrac) Field(name name.Name) Value {
	switch name {
	case names.Num:
		return n.Num
	case names.Denom:
		return n.Denom
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathFrac) HasField(name name.Name) bool {
	switch name {
	case names.Num:
		return true
	case names.Denom:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathFrac) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Num.String()), n.Field(names.Num))
	fields.Elems.Put(Str(names.Denom.String()), n.Field(names.Denom))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathFrac) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathFrac) GetLabel() *Label {
	return n.Label
}

func (n *MathFrac) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathFrac) && !w.visit() {
		return w.live()
	}
	if n.Num != nil && !n.Num.inspect(w) {
		return false
	}
	if n.Denom != nil && !n.Denom.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathLr) Kind() ElemKind { return KindMathLr }

func (n *MathLr) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Size:
		if n.Size == nil {
			return nil
		}
		return n.Size
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathLr) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Size:
		return n.Size != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathLr) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Size); f != nil {
		fields.Elems.Put(Str(names.Size.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathLr) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathLr) GetLabel() *Label {
	return n.Label
}

func (n *MathLr) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathLr) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathMat) Kind() ElemKind { return KindMathMat }

func (n *MathMat) Field(name name.Name) Value {
	switch name {
	case names.Rows:
		vs := make([]Value, len(n.Rows))
		for i, row := range n.Rows {
			rvs := make([]Value, len(row))
			for j, v := range row {
				rvs[j] = v
			}
			vs[i] = &Array{Elems: rvs}
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathMat) HasField(name name.Name) bool {
	switch name {
	case names.Rows:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathMat) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Rows.String()), n.Field(names.Rows))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathMat) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathMat) GetLabel() *Label {
	return n.Label
}

func (n *MathMat) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathMat) && !w.visit() {
		return w.live()
	}
	for _, row := range n.Rows {
		for _, c := range row {
			if !c.inspect(w) {
				return false
			}
		}
	}
	w.pop()
	return true
}

func (n *MathMid) Kind() ElemKind { return KindMathMid }

func (n *MathMid) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathMid) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathMid) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathMid) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathMid) GetLabel() *Label {
	return n.Label
}

func (n *MathMid) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathMid) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathOp) Kind() ElemKind { return KindMathOp }

func (n *MathOp) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return n.Text
	case names.Limits:
		return Bool(n.Limits)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathOp) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Limits:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathOp) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	fields.Elems.Put(Str(names.Limits.String()), n.Field(names.Limits))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathOp) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathOp) GetLabel() *Label {
	return n.Label
}

func (n *MathOp) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathOp) && !w.visit() {
		return w.live()
	}
	if n.Text != nil && !n.Text.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathPrimes) Kind() ElemKind { return KindMathPrimes }

func (n *MathPrimes) Field(name name.Name) Value {
	switch name {
	case names.Base:
		return n.Base
	case names.Count:
		return Int(n.Count)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathPrimes) HasField(name name.Name) bool {
	switch name {
	case names.Base:
		return true
	case names.Count:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathPrimes) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Base.String()), n.Field(names.Base))
	fields.Elems.Put(Str(names.Count.String()), n.Field(names.Count))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathPrimes) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathPrimes) GetLabel() *Label {
	return n.Label
}

func (n *MathPrimes) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathPrimes) && !w.visit() {
		return w.live()
	}
	if n.Base != nil && !n.Base.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathRoot) Kind() ElemKind { return KindMathRoot }

func (n *MathRoot) Field(name name.Name) Value {
	switch name {
	case names.Index:
		if n.Index == nil {
			return nil
		}
		return n.Index
	case names.Radicand:
		return n.Radicand
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathRoot) HasField(name name.Name) bool {
	switch name {
	case names.Index:
		return n.Index != nil
	case names.Radicand:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathRoot) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Index); f != nil {
		fields.Elems.Put(Str(names.Index.String()), f)
	}
	fields.Elems.Put(Str(names.Radicand.String()), n.Field(names.Radicand))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathRoot) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathRoot) GetLabel() *Label {
	return n.Label
}

func (n *MathRoot) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathRoot) && !w.visit() {
		return w.live()
	}
	if n.Index != nil && !n.Index.inspect(w) {
		return false
	}
	if n.Radicand != nil && !n.Radicand.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathText) Kind() ElemKind { return KindMathText }

func (n *MathText) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return Str(n.Text)
	case names.Bold:
		if n.Bold == nil {
			return nil
		}
		return n.Bold
	case names.Italic:
		if n.Italic == nil {
			return nil
		}
		return n.Italic
	case names.Variant:
		if n.Variant == nil {
			return nil
		}
		return n.Variant
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathText) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Bold:
		return n.Bold != nil
	case names.Italic:
		return n.Italic != nil
	case names.Variant:
		return n.Variant != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathText) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	if f := n.Field(names.Bold); f != nil {
		fields.Elems.Put(Str(names.Bold.String()), f)
	}
	if f := n.Field(names.Italic); f != nil {
		fields.Elems.Put(Str(names.Italic.String()), f)
	}
	if f := n.Field(names.Variant); f != nil {
		fields.Elems.Put(Str(names.Variant.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathText) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathText) GetLabel() *Label {
	return n.Label
}

func (n *MathText) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathText) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *MathUnderline) Kind() ElemKind { return KindMathUnderline }

func (n *MathUnderline) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathUnderline) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathUnderline) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathUnderline) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathUnderline) GetLabel() *Label {
	return n.Label
}

func (n *MathUnderline) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathUnderline) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *MathVec) Kind() ElemKind { return KindMathVec }

func (n *MathVec) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *MathVec) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *MathVec) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *MathVec) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *MathVec) GetLabel() *Label {
	return n.Label
}

func (n *MathVec) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMathVec) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *Metadata) Kind() ElemKind { return KindMetadata }

func (n *Metadata) Field(name name.Name) Value {
	switch name {
	case names.Value:
		return n.Value
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Metadata) HasField(name name.Name) bool {
	switch name {
	case names.Value:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Metadata) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Value.String()), n.Field(names.Value))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Metadata) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Metadata) GetLabel() *Label {
	return n.Label
}

func (n *Metadata) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindMetadata) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Par) Kind() ElemKind { return KindPar }

func (n *Par) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Par) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Par) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Par) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Par) GetLabel() *Label {
	return n.Label
}

func (n *Par) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindPar) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Parbreak) Kind() ElemKind { return KindParbreak }

func (n *Parbreak) Field(name name.Name) Value {
	return nil
}

func (n *Parbreak) HasField(name name.Name) bool {
	return false
}

func (n *Parbreak) Fields() *Dict {
	return new(Dict)
}

func (n *Parbreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Parbreak) GetLabel() *Label {
	return nil
}

func (n *Parbreak) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindParbreak) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Raw) Kind() ElemKind { return KindRaw }

func (n *Raw) Field(name name.Name) Value {
	switch name {
	case names.Block:
		return Bool(n.Block)
	case names.Lang:
		if n.Lang == "" {
			return nil
		}
		return Str(n.Lang)
	case names.Text:
		return Str(n.Text)
	default:
		return nil
	}
}

func (n *Raw) HasField(name name.Name) bool {
	switch name {
	case names.Block:
		return true
	case names.Lang:
		return n.Lang != ""
	case names.Text:
		return true
	default:
		return false
	}
}

func (n *Raw) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	if f := n.Field(names.Lang); f != nil {
		fields.Elems.Put(Str(names.Lang.String()), f)
	}
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	return fields
}

func (n *Raw) SetLabel(label *Label) *Label {
	return nil
}

func (n *Raw) GetLabel() *Label {
	return nil
}

func (n *Raw) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindRaw) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Ref) Kind() ElemKind { return KindRef }

func (n *Ref) Field(name name.Name) Value {
	switch name {
	case names.Target:
		return Str(n.Target.String())
	case names.Supplement:
		if n.Supplement == nil {
			return nil
		}
		return n.Supplement
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Ref) HasField(name name.Name) bool {
	switch name {
	case names.Target:
		return true
	case names.Supplement:
		return n.Supplement != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Ref) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Target.String()), n.Field(names.Target))
	if f := n.Field(names.Supplement); f != nil {
		fields.Elems.Put(Str(names.Supplement.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Ref) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Ref) GetLabel() *Label {
	return n.Label
}

func (n *Ref) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindRef) && !w.visit() {
		return w.live()
	}
	if n.Supplement != nil && !n.Supplement.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Sequence) Kind() ElemKind { return KindSequence }

func (n *Sequence) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Sequence) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Sequence) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Sequence) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Sequence) GetLabel() *Label {
	return n.Label
}

func (n *Sequence) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindSequence) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *SmartQuote) Kind() ElemKind { return KindSmartQuote }

func (n *SmartQuote) Field(name name.Name) Value {
	switch name {
	case names.Double:
		return Bool(n.Double)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *SmartQuote) HasField(name name.Name) bool {
	switch name {
	case names.Double:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *SmartQuote) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Double.String()), n.Field(names.Double))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *SmartQuote) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *SmartQuote) GetLabel() *Label {
	return n.Label
}

func (n *SmartQuote) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindSmartQuote) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Strong) Kind() ElemKind { return KindStrong }

func (n *Strong) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Strong) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Strong) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Strong) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Strong) GetLabel() *Label {
	return n.Label
}

func (n *Strong) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindStrong) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Table) Kind() ElemKind { return KindTable }

func (n *Table) Field(name name.Name) Value {
	switch name {
	case names.Columns:
		return Int(n.Columns)
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Table) HasField(name name.Name) bool {
	switch name {
	case names.Columns:
		return true
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Table) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Columns.String()), n.Field(names.Columns))
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Table) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Table) GetLabel() *Label {
	return n.Label
}

func (n *Table) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindTable) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *TableHeader) Kind() ElemKind { return KindTableHeader }

func (n *TableHeader) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *TableHeader) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *TableHeader) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *TableHeader) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *TableHeader) GetLabel() *Label {
	return n.Label
}

func (n *TableHeader) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindTableHeader) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *TermItem) Kind() ElemKind { return KindTermItem }

func (n *TermItem) Field(name name.Name) Value {
	switch name {
	case names.Term:
		return n.Term
	case names.Description:
		return n.Description
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *TermItem) HasField(name name.Name) bool {
	switch name {
	case names.Term:
		return true
	case names.Description:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *TermItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Term.String()), n.Field(names.Term))
	fields.Elems.Put(Str(names.Description.String()), n.Field(names.Description))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *TermItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *TermItem) GetLabel() *Label {
	return n.Label
}

func (n *TermItem) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindTermItem) && !w.visit() {
		return w.live()
	}
	if n.Term != nil && !n.Term.inspect(w) {
		return false
	}
	if n.Description != nil && !n.Description.inspect(w) {
		return false
	}
	w.pop()
	return true
}

func (n *Terms) Kind() ElemKind { return KindTerms }

func (n *Terms) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Terms) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Terms) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Terms) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Terms) GetLabel() *Label {
	return n.Label
}

func (n *Terms) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindTerms) && !w.visit() {
		return w.live()
	}
	for _, c := range n.Children {
		if !c.inspect(w) {
			return false
		}
	}
	w.pop()
	return true
}

func (n *Text) Kind() ElemKind { return KindText }

func (n *Text) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return Str(n.Text)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Text) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Text) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Text) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Text) GetLabel() *Label {
	return n.Label
}

func (n *Text) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindText) && !w.visit() {
		return w.live()
	}
	w.pop()
	return true
}

func (n *Underline) Kind() ElemKind { return KindUnderline }

func (n *Underline) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Underline) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Underline) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Underline) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Underline) GetLabel() *Label {
	return n.Label
}

func (n *Underline) inspect(w *walker) bool {
	w.push(n)
	if w.kinds.Contains(KindUnderline) && !w.visit() {
		return w.live()
	}
	if n.Body != nil && !n.Body.inspect(w) {
		return false
	}
	w.pop()
	return true
}
