// Code generated by fieldaccessgen. DO NOT EDIT.

package value

import "znkr.io/writst/internal/names"
import "znkr.io/writst/name"

func (n *Emph) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Emph) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Emph) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Emph) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Enum) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Enum) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Enum) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Enum) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *EnumItem) Field(name name.Name) Value {
	switch name {
	case names.Number:
		if n.Number < 0 {
			return nil
		}
		return Int(n.Number)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *EnumItem) HasField(name name.Name) bool {
	switch name {
	case names.Number:
		return n.Number >= 0
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *EnumItem) Fields() *Dict {
	fields := new(Dict)
	if f := n.Field(names.Number); f != nil {
		fields.Elems.Put(Str(names.Number.String()), f)
	}
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *EnumItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Heading) Field(name name.Name) Value {
	switch name {
	case names.Depth:
		return Int(n.Depth)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Heading) HasField(name name.Name) bool {
	switch name {
	case names.Depth:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Heading) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Depth.String()), n.Field(names.Depth))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Heading) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Linebreak) Field(name name.Name) Value {
	return nil
}

func (n *Linebreak) HasField(name name.Name) bool {
	return false
}

func (n *Linebreak) Fields() *Dict {
	return new(Dict)
}

func (n *Linebreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Link) Field(name name.Name) Value {
	switch name {
	case names.Dest:
		return Str(n.Dest)
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Link) HasField(name name.Name) bool {
	switch name {
	case names.Dest:
		return true
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Link) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Dest.String()), n.Field(names.Dest))
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Link) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *List) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *List) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *List) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *List) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *ListItem) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *ListItem) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *ListItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *ListItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Parbreak) Field(name name.Name) Value {
	return nil
}

func (n *Parbreak) HasField(name name.Name) bool {
	return false
}

func (n *Parbreak) Fields() *Dict {
	return new(Dict)
}

func (n *Parbreak) SetLabel(label *Label) *Label {
	return nil
}

func (n *Raw) Field(name name.Name) Value {
	switch name {
	case names.Block:
		return Bool(n.Block)
	case names.Lang:
		if n.Lang == "" {
			return nil
		}
		return Str(n.Lang)
	case names.Text:
		return Str(n.Text)
	default:
		return nil
	}
}

func (n *Raw) HasField(name name.Name) bool {
	switch name {
	case names.Block:
		return true
	case names.Lang:
		return n.Lang != ""
	case names.Text:
		return true
	default:
		return false
	}
}

func (n *Raw) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Block.String()), n.Field(names.Block))
	if f := n.Field(names.Lang); f != nil {
		fields.Elems.Put(Str(names.Lang.String()), f)
	}
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	return fields
}

func (n *Raw) SetLabel(label *Label) *Label {
	return nil
}

func (n *Ref) Field(name name.Name) Value {
	switch name {
	case names.Target:
		return Str(n.Target.String())
	case names.Supplement:
		if n.Supplement == nil {
			return nil
		}
		return n.Supplement
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Ref) HasField(name name.Name) bool {
	switch name {
	case names.Target:
		return true
	case names.Supplement:
		return n.Supplement != nil
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Ref) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Target.String()), n.Field(names.Target))
	if f := n.Field(names.Supplement); f != nil {
		fields.Elems.Put(Str(names.Supplement.String()), f)
	}
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Ref) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Sequence) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Sequence) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Sequence) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Sequence) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Strong) Field(name name.Name) Value {
	switch name {
	case names.Body:
		return n.Body
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Strong) HasField(name name.Name) bool {
	switch name {
	case names.Body:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Strong) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Body.String()), n.Field(names.Body))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Strong) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Table) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Table) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Table) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Table) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *TermItem) Field(name name.Name) Value {
	switch name {
	case names.Term:
		return n.Term
	case names.Description:
		return n.Description
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *TermItem) HasField(name name.Name) bool {
	switch name {
	case names.Term:
		return true
	case names.Description:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *TermItem) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Term.String()), n.Field(names.Term))
	fields.Elems.Put(Str(names.Description.String()), n.Field(names.Description))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *TermItem) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Terms) Field(name name.Name) Value {
	switch name {
	case names.Children:
		vs := make([]Value, len(n.Children))
		for i, v := range n.Children {
			vs[i] = v
		}
		return &Array{Elems: vs}
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Terms) HasField(name name.Name) bool {
	switch name {
	case names.Children:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Terms) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Children.String()), n.Field(names.Children))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Terms) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}

func (n *Text) Field(name name.Name) Value {
	switch name {
	case names.Text:
		return Str(n.Text)
	case names.Label:
		if n.Label == nil {
			return nil
		}
		return n.Label
	default:
		return nil
	}
}

func (n *Text) HasField(name name.Name) bool {
	switch name {
	case names.Text:
		return true
	case names.Label:
		return n.Label != nil
	default:
		return false
	}
}

func (n *Text) Fields() *Dict {
	fields := new(Dict)
	fields.Elems.Put(Str(names.Text.String()), n.Field(names.Text))
	if f := n.Field(names.Label); f != nil {
		fields.Elems.Put(Str(names.Label.String()), f)
	}
	return fields
}

func (n *Text) SetLabel(label *Label) *Label {
	old := n.Label
	n.Label = label
	return old
}
