package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"slices"
)

const header = `// Code generated by fieldaccessgen. DO NOT EDIT.

package value

import "znkr.io/writst/internal/names"
import "unique"

`

func main() {
	out, err := generate("content.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("content_gen.go", out, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

type FieldInfo struct {
	Name     string
	Type     string
	Required bool
}

func getFields(fset *token.FileSet, file *ast.File, typeName string) []FieldInfo {
	var fields []FieldInfo
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != typeName {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				name := field.Names[0].Name
				var typeBuf bytes.Buffer
				format.Node(&typeBuf, fset, field.Type)

				required := false
				if field.Tag != nil {
					if field.Tag.Value == "`writst:\"required\"`" {
						required = true
					}
				}

				fields = append(fields, FieldInfo{Name: name, Type: typeBuf.String(), Required: required})
			}
		}
	}
	return fields
}

func generate(filename string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing input: %v", err)
	}

	// Find all types that have an aContent() method
	var contentTypes []string
	for _, decl := range file.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if funcDecl.Name.Name != "aContent" {
			continue
		}
		if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
			continue
		}

		recvType := funcDecl.Recv.List[0].Type
		var typeName string
		switch t := recvType.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}

		if typeName != "" {
			contentTypes = append(contentTypes, typeName)
		}
	}

	slices.Sort(contentTypes)

	var buf bytes.Buffer
	buf.WriteString(header)

	for _, typeName := range contentTypes {
		fields := getFields(fset, file, typeName)

		// Field method
		fmt.Fprintf(&buf, "func (n *%s) Field(name unique.Handle[string]) Value {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tswitch name {\n")
			for _, f := range fields {
				fmt.Fprintf(&buf, "\tcase names.%s:\n", f.Name)
				switch f.Type {
				case "int":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s < 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn Int(n.%s)\n", f.Name)
				case "bool":
					fmt.Fprintf(&buf, "\t\treturn Bool(n.%s)\n", f.Name)
				case "string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == \"\" { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn Str(n.%s)\n", f.Name)
				case "[]string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif len(n.%s) == 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\tvs := make([]Value, len(n.%s))\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfor i, v := range n.%s { vs[i] = Str(v) }\n", f.Name)
					fmt.Fprintf(&buf, "\t\treturn &Array{Elems: vs}\n")
				case "[]Content", "[]*ListItem", "[]*EnumItem", "[]*TermItem":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif len(n.%s) == 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\tvs := make([]Value, len(n.%s))\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfor i, v := range n.%s { vs[i] = v }\n", f.Name)
					fmt.Fprintf(&buf, "\t\treturn &Array{Elems: vs}\n")
				case "*Label":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "Content":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "unique.Handle[string]":
					fmt.Fprintf(&buf, "\t\treturn Str(n.%s.Value())\n", f.Name)
				default:
					panic(fmt.Sprintf("unknown type %s for field %s in %s", f.Type, f.Name, typeName))
				}
			}
			fmt.Fprintf(&buf, "\tdefault:\n\t\treturn nil\n\t}\n")
		} else {
			fmt.Fprintf(&buf, "\treturn nil\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// HasField method
		fmt.Fprintf(&buf, "func (n *%s) HasField(name unique.Handle[string]) bool {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tswitch name {\n")
			for _, f := range fields {
				fmt.Fprintf(&buf, "\tcase names.%s:\n", f.Name)
				switch f.Type {
				case "int":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s >= 0\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "bool":
					fmt.Fprintf(&buf, "\t\treturn true\n")
				case "string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s != \"\"\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "[]string", "[]Content", "[]*ListItem", "[]*EnumItem", "[]*TermItem":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn len(n.%s) > 0\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "*Label", "Content":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s != nil\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "unique.Handle[string]":
					fmt.Fprintf(&buf, "\t\treturn true\n")
				default:
					panic(fmt.Sprintf("unknown type %s for field %s in %s", f.Type, f.Name, typeName))
				}
			}
			fmt.Fprintf(&buf, "\tdefault:\n\t\treturn false\n\t}\n")
		} else {
			fmt.Fprintf(&buf, "\treturn false\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// Fields method
		fmt.Fprintf(&buf, "func (n *%s) Fields() *Dict {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tfields := new(Dict)\n")
			for _, f := range fields {
				if !f.Required {
					fmt.Fprintf(&buf, "\tif f := n.Field(names.%s); f != nil {\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfields.Elems.Put(Str(names.%s.Value()), f)\n", f.Name)
					fmt.Fprintf(&buf, "\t}\n")
				} else {
					fmt.Fprintf(&buf, "\tfields.Elems.Put(Str(names.%s.Value()), n.Field(names.%s))\n", f.Name, f.Name)
				}
			}
			fmt.Fprintf(&buf, "\treturn fields\n")
		} else {
			fmt.Fprintf(&buf, "\treturn new(Dict)\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// SetLabel method
		fmt.Fprintf(&buf, "func (n *%s) SetLabel(label *Label) *Label {\n", typeName)
		hasLabel := false
		for _, f := range fields {
			if f.Name == "Label" && f.Type == "*Label" {
				hasLabel = true
				break
			}
		}
		if hasLabel {
			fmt.Fprintf(&buf, "\told := n.Label\n")
			fmt.Fprintf(&buf, "\tn.Label = label\n")
			fmt.Fprintf(&buf, "\treturn old\n")
		} else {
			fmt.Fprintf(&buf, "\treturn nil\n")
		}
		fmt.Fprintf(&buf, "}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting result: %v\n%s", err, buf.String())
	}

	return formatted, nil
}
