// Copyright 2026 Florian Zenker (flo@znkr.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"slices"
)

const header = `// Code generated by fieldaccessgen. DO NOT EDIT.

package value

import "znkr.io/markst/internal/names"
import "znkr.io/markst/name"

`

func main() {
	// content.go is the file everything is generated from; the other three
	// carry hand-written content types that need an element kind and nothing
	// else. See [generate].
	out, err := generate("content.go", "style.go", "state.go", "custom.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("content_gen.go", out, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

type FieldInfo struct {
	Name     string
	Type     string
	Required bool
}

func getFields(fset *token.FileSet, file *ast.File, typeName string) []FieldInfo {
	var fields []FieldInfo
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != typeName {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				name := field.Names[0].Name
				var typeBuf bytes.Buffer
				format.Node(&typeBuf, fset, field.Type)

				required := false
				if field.Tag != nil {
					if field.Tag.Value == "`markst:\"required\"`" {
						required = true
					}
				}

				fields = append(fields, FieldInfo{Name: name, Type: typeBuf.String(), Required: required})
			}
		}
	}
	return fields
}

// findContentTypes returns the names of the types in file that implement
// [value.Content], which the aContent method identifies.
func findContentTypes(file *ast.File) []string {
	var types []string
	for _, decl := range file.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok || funcDecl.Name.Name != "aContent" {
			continue
		}
		if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
			continue
		}
		var typeName string
		switch t := funcDecl.Recv.List[0].Type.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}
		if typeName != "" {
			types = append(types, typeName)
		}
	}
	return types
}

// writeElemKinds emits the ElemKind enum over every content type there is. The
// order is the sorted type list, so adding an element renumbers the ones after
// it — nothing may persist a kind.
func writeElemKinds(buf *bytes.Buffer, types []string) {
	fmt.Fprintf(buf, "// ElemKind identifies a content element's type, one constant per element.\n")
	fmt.Fprintf(buf, "// It is what a [KindSet] holds and what a walk filters on.\n")
	fmt.Fprintf(buf, "type ElemKind uint8\n\n")
	fmt.Fprintf(buf, "const (\n")
	for i, t := range types {
		if i == 0 {
			fmt.Fprintf(buf, "\tKind%s ElemKind = iota\n", t)
		} else {
			fmt.Fprintf(buf, "\tKind%s\n", t)
		}
	}
	fmt.Fprintf(buf, "\n\t// numElemKinds is the number of element kinds. A KindSet holds one bit\n")
	fmt.Fprintf(buf, "\t// per kind, so it must not exceed 64; TestKindSetFits checks that.\n")
	fmt.Fprintf(buf, "\tnumElemKinds\n)\n\n")
}

// generate emits the per-element code for the content types in filename, plus
// the element-kind enum, which covers the content types in extra too: a kind
// numbers every element there is, including the four whose other methods are
// written by hand.
func generate(filename string, extra ...string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing input: %v", err)
	}

	contentTypes := findContentTypes(file)
	slices.Sort(contentTypes)

	allTypes := slices.Clone(contentTypes)
	for _, name := range extra {
		f, err := parser.ParseFile(fset, name, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parsing input: %v", err)
		}
		allTypes = append(allTypes, findContentTypes(f)...)
	}
	slices.Sort(allTypes)

	var buf bytes.Buffer
	buf.WriteString(header)
	writeElemKinds(&buf, allTypes)

	for _, typeName := range contentTypes {
		fields := getFields(fset, file, typeName)

		fmt.Fprintf(&buf, "func (n *%s) Kind() ElemKind { return Kind%s }\n\n", typeName, typeName)

		// Field method
		fmt.Fprintf(&buf, "func (n *%s) Field(name name.Name) Value {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tswitch name {\n")
			for _, f := range fields {
				fmt.Fprintf(&buf, "\tcase names.%s:\n", f.Name)
				switch f.Type {
				case "int":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s < 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn Int(n.%s)\n", f.Name)
				case "bool":
					fmt.Fprintf(&buf, "\t\treturn Bool(n.%s)\n", f.Name)
				case "string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == \"\" { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn Str(n.%s)\n", f.Name)
				case "[]string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif len(n.%s) == 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\tvs := make([]Value, len(n.%s))\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfor i, v := range n.%s { vs[i] = Str(v) }\n", f.Name)
					fmt.Fprintf(&buf, "\t\treturn &Array{Elems: vs}\n")
				case "[]Content", "[]*ListItem", "[]*EnumItem", "[]*TermItem":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif len(n.%s) == 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\tvs := make([]Value, len(n.%s))\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfor i, v := range n.%s { vs[i] = v }\n", f.Name)
					fmt.Fprintf(&buf, "\t\treturn &Array{Elems: vs}\n")
				case "[][]Content":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif len(n.%s) == 0 { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\tvs := make([]Value, len(n.%s))\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfor i, row := range n.%s {\n", f.Name)
					fmt.Fprintf(&buf, "\t\t\trvs := make([]Value, len(row))\n")
					fmt.Fprintf(&buf, "\t\t\tfor j, v := range row { rvs[j] = v }\n")
					fmt.Fprintf(&buf, "\t\t\tvs[i] = &Array{Elems: rvs}\n")
					fmt.Fprintf(&buf, "\t\t}\n")
					fmt.Fprintf(&buf, "\t\treturn &Array{Elems: vs}\n")
				case "*Label":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "*Dict":
					// A dict field is already a Value; an unset one is nil,
					// and an empty one is a dict the document wrote itself.
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "Content", "Value":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "*Datetime":
					// The pointer is only the struct's encoding of "unset": a
					// Datetime is a value type in the value world, and every
					// datetime method asserts value.Datetime, so hand out the
					// pointee rather than the pointer.
					if !f.Required {
						fmt.Fprintf(&buf, "\t\tif n.%s == nil { return nil }\n", f.Name)
					}
					fmt.Fprintf(&buf, "\t\treturn *n.%s\n", f.Name)
				case "Length":
					fmt.Fprintf(&buf, "\t\treturn n.%s\n", f.Name)
				case "name.Name":
					fmt.Fprintf(&buf, "\t\treturn Str(n.%s.String())\n", f.Name)
				default:
					panic(fmt.Sprintf("unknown type %s for field %s in %s", f.Type, f.Name, typeName))
				}
			}
			fmt.Fprintf(&buf, "\tdefault:\n\t\treturn nil\n\t}\n")
		} else {
			fmt.Fprintf(&buf, "\treturn nil\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// HasField method
		fmt.Fprintf(&buf, "func (n *%s) HasField(name name.Name) bool {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tswitch name {\n")
			for _, f := range fields {
				fmt.Fprintf(&buf, "\tcase names.%s:\n", f.Name)
				switch f.Type {
				case "int":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s >= 0\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "bool":
					fmt.Fprintf(&buf, "\t\treturn true\n")
				case "string":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s != \"\"\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "[]string", "[]Content", "[]*ListItem", "[]*EnumItem", "[]*TermItem", "[][]Content":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn len(n.%s) > 0\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "*Label", "*Dict", "Content", "Value", "*Datetime":
					if !f.Required {
						fmt.Fprintf(&buf, "\t\treturn n.%s != nil\n", f.Name)
					} else {
						fmt.Fprintf(&buf, "\t\treturn true\n")
					}
				case "Length", "name.Name":
					fmt.Fprintf(&buf, "\t\treturn true\n")
				default:
					panic(fmt.Sprintf("unknown type %s for field %s in %s", f.Type, f.Name, typeName))
				}
			}
			fmt.Fprintf(&buf, "\tdefault:\n\t\treturn false\n\t}\n")
		} else {
			fmt.Fprintf(&buf, "\treturn false\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// Fields method
		fmt.Fprintf(&buf, "func (n *%s) Fields() *Dict {\n", typeName)
		if len(fields) > 0 {
			fmt.Fprintf(&buf, "\tfields := new(Dict)\n")
			for _, f := range fields {
				if !f.Required {
					fmt.Fprintf(&buf, "\tif f := n.Field(names.%s); f != nil {\n", f.Name)
					fmt.Fprintf(&buf, "\t\tfields.Elems.Put(Str(names.%s.String()), f)\n", f.Name)
					fmt.Fprintf(&buf, "\t}\n")
				} else {
					fmt.Fprintf(&buf, "\tfields.Elems.Put(Str(names.%s.String()), n.Field(names.%s))\n", f.Name, f.Name)
				}
			}
			fmt.Fprintf(&buf, "\treturn fields\n")
		} else {
			fmt.Fprintf(&buf, "\treturn new(Dict)\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// SetLabel/GetLabel methods
		hasLabel := false
		for _, f := range fields {
			if f.Name == "Label" && f.Type == "*Label" {
				hasLabel = true
				break
			}
		}
		fmt.Fprintf(&buf, "func (n *%s) SetLabel(label *Label) *Label {\n", typeName)
		if hasLabel {
			fmt.Fprintf(&buf, "\told := n.Label\n")
			fmt.Fprintf(&buf, "\tn.Label = label\n")
			fmt.Fprintf(&buf, "\treturn old\n")
		} else {
			fmt.Fprintf(&buf, "\treturn nil\n")
		}
		fmt.Fprintf(&buf, "}\n\n")
		fmt.Fprintf(&buf, "func (n *%s) GetLabel() *Label {\n", typeName)
		if hasLabel {
			fmt.Fprintf(&buf, "\treturn n.Label\n")
		} else {
			fmt.Fprintf(&buf, "\treturn nil\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// inspect method: offers the node to the walker, then descends into its
		// content fields in declaration order, which is document order. Recursing
		// here rather than handing back a slice of children keeps the traversal
		// allocation-free — the walker is passed down untouched, so nothing is
		// built along the way. See [Preorder].
		fmt.Fprintf(&buf, "func (n *%s) inspect(w *walker) bool {\n", typeName)
		fmt.Fprintf(&buf, "\tw.push(n)\n")
		fmt.Fprintf(&buf, "\tif w.kinds.Contains(Kind%s) && !w.visit() { return w.live() }\n", typeName)
		for _, f := range fields {
			switch f.Type {
			case "Content":
				// Nil-checked whether or not the field is required: a half-built
				// node is not worth a panic in a walk.
				fmt.Fprintf(&buf, "\tif n.%s != nil && !n.%s.inspect(w) { return false }\n", f.Name, f.Name)
			case "[]Content", "[]*ListItem", "[]*EnumItem", "[]*TermItem":
				fmt.Fprintf(&buf, "\tfor _, c := range n.%s {\n", f.Name)
				fmt.Fprintf(&buf, "\t\tif !c.inspect(w) { return false }\n")
				fmt.Fprintf(&buf, "\t}\n")
			case "[][]Content":
				fmt.Fprintf(&buf, "\tfor _, row := range n.%s {\n", f.Name)
				fmt.Fprintf(&buf, "\t\tfor _, c := range row {\n")
				fmt.Fprintf(&buf, "\t\t\tif !c.inspect(w) { return false }\n")
				fmt.Fprintf(&buf, "\t\t}\n")
				fmt.Fprintf(&buf, "\t}\n")
			}
		}
		fmt.Fprintf(&buf, "\tw.pop()\n")
		fmt.Fprintf(&buf, "\treturn true\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting result: %v\n%s", err, buf.String())
	}

	return formatted, nil
}
