package names

import "unique"

var (
	Array       = unique.Make("array")
	Arguments   = unique.Make("arguments")
	At          = unique.Make("at")
	Base        = unique.Make("base")
	Block       = unique.Make("block")
	Body        = unique.Make("body")
	Bytes       = unique.Make("bytes")
	Children    = unique.Make("children")
	Count       = unique.Make("count")
	Decimal     = unique.Make("decimal")
	Default     = unique.Make("default")
	Depth       = unique.Make("depth")
	Description = unique.Make("description")
	Dest        = unique.Make("dest")
	Endian      = unique.Make("endian")
	Float       = unique.Make("float")
	FromBytes   = unique.Make("from-bytes")
	Inf         = unique.Make("inf")
	Int         = unique.Make("int")
	IsInfinite  = unique.Make("is-infinite")
	IsNan       = unique.Make("is-nan")
	Join        = unique.Make("join")
	Label       = unique.Make("label")
	Lang        = unique.Make("lang")
	Last        = unique.Make("last")
	Len         = unique.Make("len")
	Lines       = unique.Make("lines")
	Nan         = unique.Make("nan")
	Number      = unique.Make("number")
	Range       = unique.Make("range")
	Repr        = unique.Make("repr")
	Separator   = unique.Make("separator")
	Signed      = unique.Make("signed")
	Signum      = unique.Make("signum")
	Size        = unique.Make("size")
	Slice       = unique.Make("slice")
	Step        = unique.Make("step")
	Str         = unique.Make("str")
	Sum         = unique.Make("sum")
	Supplement  = unique.Make("supplement")
	Target      = unique.Make("target")
	Term        = unique.Make("term")
	Text        = unique.Make("text")
	ToBytes     = unique.Make("to-bytes")
	Type        = unique.Make("type")
)
