package names

import "unique"

var (
	Array      = unique.Make("array")
	Base       = unique.Make("base")
	Bytes      = unique.Make("bytes")
	Count      = unique.Make("count")
	Decimal    = unique.Make("decimal")
	Default    = unique.Make("default")
	Endian     = unique.Make("endian")
	Float      = unique.Make("float")
	FromBytes  = unique.Make("from-bytes")
	Inf        = unique.Make("inf")
	Int        = unique.Make("int")
	IsNan      = unique.Make("is-nan")
	IsInfinite = unique.Make("is-infinite")
	Join       = unique.Make("join")
	Last       = unique.Make("last")
	Nan        = unique.Make("nan")
	Range      = unique.Make("range")
	Repr       = unique.Make("repr")
	Separator  = unique.Make("separator")
	Signed     = unique.Make("signed")
	Signum     = unique.Make("signum")
	Size       = unique.Make("size")
	Slice      = unique.Make("slice")
	Step       = unique.Make("step")
	Str        = unique.Make("str")
	ToBytes    = unique.Make("to-bytes")
	Type       = unique.Make("type")
)
