// Copyright 2026 Florian Zenker (flo@znkr.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// The content of this file is derived from the Go project's
// src/internal/copyright/copyright_test.go.

package copyright

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

var copyright = []byte("// Copyright")

var permitted = [][]byte{
	[]byte("// Code generated by "),
}

var rootOnce sync.Once
var root string

func moduleRoot() string {
	rootOnce.Do(func() {
		dir, err := os.Getwd()
		if err != nil {
			panic(fmt.Sprintf("getting working directory: %v", err))
		}
		for dir != "/" {
			data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
			if err != nil {
				if os.IsNotExist(err) {
					dir = filepath.Dir(dir)
					continue
				}
				panic(fmt.Sprintf("opening go.mod file: %v", err))
			}
			if strings.HasPrefix(string(data), "module znkr.io/markst") {
				root = dir
				return
			}
		}
		panic("znkr.io/markst module root not found")
	})
	return root
}

func TestCopyright(t *testing.T) {
	buf := make([]byte, 2048)
	filepath.WalkDir(moduleRoot(), func(path string, d fs.DirEntry, _ error) error {
		if d.IsDir() && d.Name() == "testdata" {
			return filepath.SkipDir
		}

		switch filepath.Ext(d.Name()) {
		default:
			return nil
		case ".s", ".go":
			// check
		}

		f, err := os.Open(path)
		if err != nil {
			t.Error(err)
			return nil
		}
		defer f.Close()
		n, err := f.Read(buf)
		if err != nil && err != io.EOF {
			t.Error(err)
			return nil
		}
		b := buf[:n]
		if bytes.HasPrefix(b, copyright) {
			for l := range bytes.Lines(b) {
				if !bytes.HasPrefix(l, []byte("//")) {
					if !bytes.Equal(l, []byte("\n")) {
						t.Errorf("%s: missing newline after copyright notice", path)
					}
					break
				}
			}
			return nil
		}
		for _, ok := range permitted {
			if bytes.HasPrefix(b, ok) {
				return nil
			}
		}
		t.Errorf("%s: missing copyright notice", path)
		return nil
	})
}
