// Code generated by "stringer -type Kind"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindNone-0]
	_ = x[KindAuto-1]
	_ = x[KindBool-2]
	_ = x[KindInt-3]
	_ = x[KindFloat-4]
	_ = x[KindNumeric-5]
	_ = x[KindString-6]
	_ = x[KindArray-7]
	_ = x[KindDict-8]
	_ = x[KindFunction-9]
	_ = x[KindArguments-10]
	_ = x[KindContent-11]
}

const _Kind_name = "KindNoneKindAutoKindBoolKindIntKindFloatKindNumericKindStringKindArrayKindDictKindFunctionKindArgumentsKindContent"

var _Kind_index = [...]uint8{0, 8, 16, 24, 31, 40, 51, 61, 70, 78, 90, 103, 114}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
