// Copyright 2026 Florian Zenker (flo@znkr.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package names provides interned string handles for Markst identifiers used as
// function names, method names, and parameter names throughout the ir package.
// Using [unique.Handle] avoids repeated string comparisons during evaluation
// and field lookup.
package names

import "znkr.io/markst/name"

var (
	Abs         = name.Make("abs")
	Accent      = name.Make("accent")
	Align       = name.Make("align")
	Alt         = name.Make("alt")
	Amount      = name.Make("amount")
	Angle       = name.Make("angle")
	Arguments   = name.Make("arguments")
	Array       = name.Make("array")
	Assert      = name.Make("assert")
	At          = name.Make("at")
	Attrs       = name.Make("attrs")
	Augment     = name.Make("augment")
	Base        = name.Make("base")
	Bb          = name.Make("bb")
	Block       = name.Make("block")
	Body        = name.Make("body")
	Bold        = name.Make("bold")
	Bottom      = name.Make("bottom")
	By          = name.Make("by")
	Bytes       = name.Make("bytes")
	Cal         = name.Make("cal")
	Calc        = name.Make("calc")
	Cancel      = name.Make("cancel")
	Cases       = name.Make("cases")
	Ceil        = name.Make("ceil")
	Children    = name.Make("children")
	Chunks      = name.Make("chunks")
	Close       = name.Make("close")
	ColumnGap   = name.Make("column-gap")
	Columns     = name.Make("columns")
	Content     = name.Make("content")
	Count       = name.Make("count")
	Date        = name.Make("date")
	Datetime    = name.Make("datetime")
	Day         = name.Make("day")
	Days        = name.Make("days")
	Decimal     = name.Make("decimal")
	Dedup       = name.Make("dedup")
	Default     = name.Make("default")
	Delim       = name.Make("delim")
	Denom       = name.Make("denom")
	Depth       = name.Make("depth")
	Description = name.Make("description")
	Dest        = name.Make("dest")
	Digits      = name.Make("digits")
	Display     = name.Make("display")
	Document    = name.Make("document")
	Dotless     = name.Make("dotless")
	Double      = name.Make("double")
	Duration    = name.Make("duration")
	Elem        = name.Make("elem")
	Emoji       = name.Make("emoji")
	Emph        = name.Make("emph")
	Endian      = name.Make("endian")
	Enum        = name.Make("enum")
	Enumerate   = name.Make("enumerate")
	Eq          = name.Make("eq")
	Equation    = name.Make("equation")
	Even        = name.Make("even")
	Exact       = name.Make("exact")
	Filter      = name.Make("filter")
	First       = name.Make("first")
	Float       = name.Make("float")
	Floor       = name.Make("floor")
	Fold        = name.Make("fold")
	Frac        = name.Make("frac")
	Fraction    = name.Make("fraction")
	Frak        = name.Make("frak")
	FromBytes   = name.Make("from-bytes")
	Function    = name.Make("function")
	Footnote    = name.Make("footnote")
	Gap         = name.Make("gap")
	H           = name.Make("h")
	Header      = name.Make("header")
	Heading     = name.Make("heading")
	Hour        = name.Make("hour")
	Hours       = name.Make("hours")
	Html        = name.Make("html")
	Image       = name.Make("image")
	Index       = name.Make("index")
	Inf         = name.Make("inf")
	Init        = name.Make("init")
	Insert      = name.Make("insert")
	Int         = name.Make("int")
	Intersperse = name.Make("intersperse")
	IsInfinite  = name.Make("is-infinite")
	IsNan       = name.Make("is-nan")
	Italic      = name.Make("italic")
	Item        = name.Make("item")
	Join        = name.Make("join")
	Key         = name.Make("key")
	Label       = name.Make("label")
	Lang        = name.Make("lang")
	Last        = name.Make("last")
	Len         = name.Make("len")
	Level       = name.Make("level")
	Limits      = name.Make("limits")
	Linebreak   = name.Make("linebreak")
	Lines       = name.Make("lines")
	Link        = name.Make("link")
	List        = name.Make("list")
	Lorem       = name.Make("lorem")
	Lr          = name.Make("lr")
	Map         = name.Make("map")
	Mat         = name.Make("mat")
	Math        = name.Make("math")
	Max         = name.Make("max")
	Metadata    = name.Make("metadata")
	Message     = name.Make("message")
	Mid         = name.Make("mid")
	Min         = name.Make("min")
	Minute      = name.Make("minute")
	Minutes     = name.Make("minutes")
	Mono        = name.Make("mono")
	Month       = name.Make("month")
	Named       = name.Make("named")
	Nan         = name.Make("nan")
	Ne          = name.Make("ne")
	Norm        = name.Make("norm")
	Num         = name.Make("num")
	Number      = name.Make("number")
	Odd         = name.Make("odd")
	Offset      = name.Make("offset")
	Op          = name.Make("op")
	Open        = name.Make("open")
	Ordinal     = name.Make("ordinal")
	Pairs       = name.Make("pairs")
	ParseDate   = name.Make("parse_date")
	Par         = name.Make("par")
	Parbreak    = name.Make("parbreak")
	Path        = name.Make("path")
	Pop         = name.Make("pop")
	Pos         = name.Make("pos")
	Position    = name.Make("position")
	Product     = name.Make("product")
	Push        = name.Make("push")
	Radicand    = name.Make("radicand")
	Range       = name.Make("range")
	Ratio       = name.Make("ratio")
	Raw         = name.Make("raw")
	Reduce      = name.Make("reduce")
	Ref         = name.Make("ref")
	Relative    = name.Make("relative")
	Rem         = name.Make("rem")
	Remove      = name.Make("remove")
	Repeat      = name.Make("repeat")
	Repr        = name.Make("repr")
	Rev         = name.Make("rev")
	Reverse     = name.Make("reverse")
	Root        = name.Make("root")
	Round       = name.Make("round")
	RowGap      = name.Make("row-gap")
	Rows        = name.Make("rows")
	Sans        = name.Make("sans")
	Second      = name.Make("second")
	Seconds     = name.Make("seconds")
	Separator   = name.Make("separator")
	Serif       = name.Make("serif")
	Signed      = name.Make("signed")
	Signum      = name.Make("signum")
	Sin         = name.Make("sin")
	Size        = name.Make("size")
	Slice       = name.Make("slice")
	Smartquote  = name.Make("smartquote")
	Sorted      = name.Make("sorted")
	Split       = name.Make("split")
	Sqrt        = name.Make("sqrt")
	Start       = name.Make("start")
	State       = name.Make("state")
	Std         = name.Make("std")
	Step        = name.Make("step")
	Str         = name.Make("str")
	Strong      = name.Make("strong")
	Sum         = name.Make("sum")
	Supplement  = name.Make("supplement")
	Sym         = name.Make("sym")
	Symbol      = name.Make("symbol")
	Tag         = name.Make("tag")
	Table       = name.Make("table")
	Target      = name.Make("target")
	Term        = name.Make("term")
	Terms       = name.Make("terms")
	Text        = name.Make("text")
	Title       = name.Make("title")
	ToBytes     = name.Make("to-bytes")
	ToDict      = name.Make("to-dict")
	Today       = name.Make("today")
	Top         = name.Make("top")
	Trim        = name.Make("trim")
	Type        = name.Make("type")
	Underline   = name.Make("underline")
	Update      = name.Make("update")
	Upright     = name.Make("upright")
	Value       = name.Make("value")
	Variant     = name.Make("variant")
	Vec         = name.Make("vec")
	Weekday     = name.Make("weekday")
	Weeks       = name.Make("weeks")
	Where       = name.Make("where")
	Windows     = name.Make("windows")
	With        = name.Make("with")
	Year        = name.Make("year")
	Zip         = name.Make("zip")
)
