// Package names provides interned string handles for Writst identifiers used as
// function names, method names, and parameter names throughout the ir package.
// Using [unique.Handle] avoids repeated string comparisons during evaluation
// and field lookup.
package names

import "unique"

var (
	Angle       = unique.Make("angle")
	Arguments   = unique.Make("arguments")
	Array       = unique.Make("array")
	At          = unique.Make("at")
	Base        = unique.Make("base")
	Block       = unique.Make("block")
	Body        = unique.Make("body")
	By          = unique.Make("by")
	Bytes       = unique.Make("bytes")
	Children    = unique.Make("children")
	Chunks      = unique.Make("chunks")
	Content     = unique.Make("content")
	Count       = unique.Make("count")
	Dedup       = unique.Make("dedup")
	Decimal     = unique.Make("decimal")
	Default     = unique.Make("default")
	Depth       = unique.Make("depth")
	Description = unique.Make("description")
	Dest        = unique.Make("dest")
	Endian      = unique.Make("endian")
	Enumerate   = unique.Make("enumerate")
	Exact       = unique.Make("exact")
	Filter      = unique.Make("filter")
	First       = unique.Make("first")
	Float       = unique.Make("float")
	Fold        = unique.Make("fold")
	Fraction    = unique.Make("fraction")
	FromBytes   = unique.Make("from-bytes")
	Function    = unique.Make("function")
	Inf         = unique.Make("inf")
	Insert      = unique.Make("insert")
	Int         = unique.Make("int")
	Intersperse = unique.Make("intersperse")
	IsInfinite  = unique.Make("is-infinite")
	IsNan       = unique.Make("is-nan")
	Join        = unique.Make("join")
	Key         = unique.Make("key")
	Label       = unique.Make("label")
	Lang        = unique.Make("lang")
	Last        = unique.Make("last")
	Len         = unique.Make("len")
	Lines       = unique.Make("lines")
	Map         = unique.Make("map")
	Nan         = unique.Make("nan")
	Number      = unique.Make("number")
	Pop         = unique.Make("pop")
	Position    = unique.Make("position")
	Product     = unique.Make("product")
	Push        = unique.Make("push")
	Range       = unique.Make("range")
	Reduce      = unique.Make("reduce")
	Ratio       = unique.Make("ratio")
	Relative    = unique.Make("relative")
	Remove      = unique.Make("remove")
	Repr        = unique.Make("repr")
	Rev         = unique.Make("rev")
	Separator   = unique.Make("separator")
	Signed      = unique.Make("signed")
	Signum      = unique.Make("signum")
	Size        = unique.Make("size")
	Slice       = unique.Make("slice")
	Sorted      = unique.Make("sorted")
	Split       = unique.Make("split")
	Start       = unique.Make("start")
	Step        = unique.Make("step")
	Str         = unique.Make("str")
	Sum         = unique.Make("sum")
	Supplement  = unique.Make("supplement")
	Target      = unique.Make("target")
	Term        = unique.Make("term")
	Text        = unique.Make("text")
	ToBytes     = unique.Make("to-bytes")
	ToDict      = unique.Make("to-dict")
	Type        = unique.Make("type")
	Windows     = unique.Make("windows")
	With        = unique.Make("with")
	Zip         = unique.Make("zip")
)
